import jsPDF from "jspdf";
import { GoodsReceipt, SalesOrder } from "../types";

/**
 * Generates and downloads a clean, professional PDF for a Goods Receipt Note (GRN)
 */
export const downloadGRNPDF = (grn: GoodsReceipt, isBangla: boolean = false) => {
  const doc = new jsPDF();

  // Primary Header Bar
  doc.setFillColor(16, 185, 129); // Emerald Green
  doc.rect(0, 0, 210, 28, "F");

  // Company Name & Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text("OITS DHAKA AGRO ERP LTD.", 14, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("GOODS RECEIPT NOTE (GRN)", 140, 18);

  // Body Text Color
  doc.setTextColor(30, 41, 59);

  // Metadata Section
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`GRN Number:`, 14, 40);
  doc.setFont("helvetica", "normal");
  doc.text(grn.grnNumber, 48, 40);

  doc.setFont("helvetica", "bold");
  doc.text(`PO Reference:`, 14, 47);
  doc.setFont("helvetica", "normal");
  doc.text(grn.poNumber, 48, 47);

  doc.setFont("helvetica", "bold");
  doc.text(`Supplier Name:`, 14, 54);
  doc.setFont("helvetica", "normal");
  doc.text(grn.supplierName, 48, 54);

  doc.setFont("helvetica", "bold");
  doc.text(`Received Date:`, 130, 40);
  doc.setFont("helvetica", "normal");
  doc.text(grn.receivedDate, 165, 40);

  doc.setFont("helvetica", "bold");
  doc.text(`Inventory Posting:`, 130, 47);
  doc.setFont("helvetica", "normal");
  doc.text(grn.postedToInventory ? "POSTED" : "PENDING", 165, 47);

  // Divider Line
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 62, 196, 62);

  // Table Header
  let y = 72;
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y - 5, 182, 9, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("ITEM CODE", 18, y);
  doc.text("ITEM DESCRIPTION", 50, y);
  doc.text("ORDERED QTY", 125, y);
  doc.text("RECEIVED QTY", 160, y);

  y += 9;
  doc.setFont("helvetica", "normal");

  grn.items.forEach((item) => {
    doc.text(item.itemCode, 18, y);
    doc.text(item.itemName.slice(0, 35), 50, y);
    doc.text(`${item.orderedQty.toLocaleString()} ${item.uom}`, 125, y);
    doc.text(`${item.receivedQty.toLocaleString()} ${item.uom}`, 160, y);
    y += 8;
  });

  // Quality Control Section
  y += 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("QUALITY ASSURANCE & INSPECTION SUMMARY:", 14, y);

  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const qcPassed = grn.items.every((i) => i.qcPassed);
  doc.text(`Quality Check Result: ${qcPassed ? "PASSED (100% Compliant)" : "REJECTED"}`, 14, y);
  
  if (grn.scannedInvoiceUrl) {
    y += 6;
    doc.text(`Digital Invoice Verification: Attached and Linked (Hash OCR Verified)`, 14, y);
  }

  // Footer / Signatures
  y += 35;
  doc.setDrawColor(203, 213, 225);
  doc.line(20, y, 70, y);
  doc.line(140, y, 190, y);

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("Authorized Warehouse Officer", 20, y + 5);
  doc.text("Quality Control Manager", 140, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by OITS Dhaka Agro ERP on ${new Date().toLocaleDateString()}`, 14, 285);

  doc.save(`${grn.grnNumber}_Goods_Receipt.pdf`);
};

/**
 * Generates and downloads a clean, professional PDF for a Sales Order (SO)
 */
export const downloadSalesOrderPDF = (so: SalesOrder, isBangla: boolean = false) => {
  const doc = new jsPDF();

  // Primary Header Bar
  doc.setFillColor(99, 102, 241); // Indigo
  doc.rect(0, 0, 210, 28, "F");

  // Company Name & Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.text("OITS DHAKA AGRO ERP LTD.", 14, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("OFFICIAL SALES ORDER (SO)", 140, 18);

  // Body Text Color
  doc.setTextColor(30, 41, 59);

  // Metadata Section
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Sales Order No:`, 14, 40);
  doc.setFont("helvetica", "normal");
  doc.text(so.orderNumber, 50, 40);

  doc.setFont("helvetica", "bold");
  doc.text(`Customer Name:`, 14, 47);
  doc.setFont("helvetica", "normal");
  doc.text(so.customerName, 50, 47);

  doc.setFont("helvetica", "bold");
  doc.text(`Customer Code:`, 14, 54);
  doc.setFont("helvetica", "normal");
  doc.text(so.customerCode, 50, 54);

  doc.setFont("helvetica", "bold");
  doc.text(`Order Date:`, 130, 40);
  doc.setFont("helvetica", "normal");
  doc.text(so.orderDate, 165, 40);

  doc.setFont("helvetica", "bold");
  doc.text(`Delivery Status:`, 130, 47);
  doc.setFont("helvetica", "normal");
  doc.text(so.deliveryStatus, 165, 47);

  doc.setFont("helvetica", "bold");
  doc.text(`Payment Status:`, 130, 54);
  doc.setFont("helvetica", "normal");
  doc.text(so.status, 165, 54);

  // Divider Line
  doc.setDrawColor(226, 232, 240);
  doc.line(14, 62, 196, 62);

  // Table Header
  let y = 72;
  doc.setFillColor(241, 245, 249);
  doc.rect(14, y - 5, 182, 9, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("PRODUCT CODE", 18, y);
  doc.text("PRODUCT DESCRIPTION", 55, y);
  doc.text("QUANTITY", 120, y);
  doc.text("UNIT PRICE (BDT)", 145, y);
  doc.text("TOTAL (BDT)", 175, y);

  y += 9;
  doc.setFont("helvetica", "normal");

  so.items.forEach((item) => {
    doc.text(item.productCode, 18, y);
    doc.text(item.productName.slice(0, 30), 55, y);
    doc.text(`${item.qty.toLocaleString()} ${item.uom}`, 120, y);
    doc.text(`BDT ${item.unitPrice.toLocaleString()}`, 145, y);
    doc.text(`BDT ${item.totalPrice.toLocaleString()}`, 175, y);
    y += 8;
  });

  // Total Summary
  y += 5;
  doc.setFillColor(248, 250, 252);
  doc.rect(120, y, 76, 12, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("TOTAL AMOUNT:", 124, y + 8);
  doc.text(`BDT ${so.totalAmount.toLocaleString()}`, 165, y + 8);

  // Terms & Conditions
  y += 25;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("TERMS & CONDITIONS:", 14, y);

  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("1. Goods once sold will be dispatched according to factory logistics schedule.", 14, y);
  y += 4;
  doc.text("2. Payments must be cleared into Bank Asia General Account prior to transit dispatch.", 14, y);

  // Signatures
  y += 30;
  doc.setDrawColor(203, 213, 225);
  doc.line(20, y, 70, y);
  doc.line(140, y, 190, y);

  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text("Commercial Sales Manager", 20, y + 5);
  doc.text("Chief Financial Officer (CFO)", 140, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by OITS Dhaka Agro ERP on ${new Date().toLocaleDateString()}`, 14, 285);

  doc.save(`${so.orderNumber}_Sales_Order.pdf`);
};
